apiVersion: apps/v1
kind: Deployment
metadata:
  name: ntlg-pustovit-deployment
  namespace: stage
spec:
  selector:
    matchLabels:
      app: ntlg-pustovit-app
  replicas: 2
  template:
    metadata:
      labels:
        app: ntlg-pustovit-app
    spec:
      containers:
       - name: ntlg-pustovit-app
         image: aleksturbo/ntlg-pstvt-app:__VERSION__
         imagePullPolicy: Always
         ports:
           - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ntlg-pustovit-service
  labels:
    app: ntlg-pustovit-service
  namespace: stage
spec:
  selector:
    app: ntlg-pustovit-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: ntlg-pustovit-service-np
  labels:
    app: ntlg-pustovit-service-np
  namespace: stage
spec:
  type: NodePort
  selector:
    app: ntlg-pustovit-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30008
