apiVersion: apps/v1
kind: Deployment
metadata:
  name: ntlg-pustovit-deployment
  namespace: stage
spec:
  selector:
    matchLabels:
      app: ntlg-pustovit-app
  replicas: 2
  template:
    metadata:
      labels:
        app: ntlg-pustovit-app
    spec:
      containers:
       - name: ntlg-pustovit-app
         image: aleksturbo/ntlg-pstvt-app:__VERSION__
         imagePullPolicy: Always
         ports:
           - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ntlg-pustovit-service
  namespace: stage
spec:
  type: LoadBalancer
  selector:
    app: ntlg-pustovit-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ntlg-pustovit-ingress
  namespace: stage
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.alb.yc.io/subnets: enp0vphumjjlsrcsubin
    ingress.alb.yc.io/security-groups: enpo332e9qt4lpv6iico
    ingress.alb.yc.io/external-ipv4-address: auto
spec:
  ingressClassName: nginx
  rules:
    - host:
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: ntlg-pustovit-service
                port:
                  number: 80