---
apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  type: LoadBalancer
  selector:
    app: ntlg-pustovit-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80